### ISSUE TITLE
Like/Unlike operation to work without page refresh

### ISSUE THREAD

**Issue by melvinlau** [melvinlau/acebook-facebuzz#60] opened 2019-11-07 16:41 UTC
Currently the like and unlike feature works but with page refresh. Next task, as required by client, is implement this without page refresh.

**Comment by JDtheGeek** [comment] 2019-11-07 16:45
Closing this one as a duplicate of the below issue that was already created:
https://github.com/melvinlau/acebook-facebuzz/issues/59

**Closed by JDtheGeek** 2019-11-07 16:45 UTC
Labels: CLIENT, UX, bug, duplicate
